// svelteversion/src/App.svelte
<script>
	import Header from './components/Header.svelte'
	import AddRecipe from './components/AddRecipe.svelte'
	import SearchRecipe from './components/SearchRecipe.svelte'
	import ListRecipes from './components/ListRecipes.svelte'

	let recipes = [{
						id: 1,
						name: 'Ensopado de galinha'  
						},
						{
						id: 2,
						name: 'Risoto'
						},
						{
						id: 3,
						name: 'strogonoff'
					}]
	
	const handleNewRecipe = () => {
		var value = prompt('Digite a nova receita');

		if(value){
			recipes = [...recipes, {id: 4, name: value}];
		}

  }
</script>

<style>

	#principal {
		display: flex;
		flex-direction: column;
	}

	#card {
		display: flex; 
    	flex-direction: row;
    	justify-content: center;
    	align-items: center;
	}

	#ListContent {
		display: flex; 
		flex-direction: column; 
		justify-content: center; 
		align-items: center;
	}

</style>

<div id="principal">
	<Header />
	<div id="card">
		<AddRecipe on:addrecipe={handleNewRecipe}/>
		<SearchRecipe />
	</div>

	<div id="ListContent">
		<h2>Receitas já adicionadas</h2>
		<ListRecipes data={recipes}/>
	</div>
</div>

// vueversion/src/App.vue
<template>
  <div id="app">
    <Header/>
    <div id="Card"> 
      <AddRecipe v-on:add-Recipe="addNewRecipe"/>
      <SearchRecipe/>
    </div>
    <div id="ListContent">
      <h2>Receitas já adicionadas</h2>
      <ListRecipes v-bind:recipes = "recipes"/>
    </div>
  </div>
</template>

<script>
import Header from './components/Header'
import AddRecipe from './components/AddRecipe'
import SearchRecipe from './components/SearchRecipe'
import ListRecipes from './components/ListRecipes'

export default {
  name: 'App',
  components: {
    Header,
    AddRecipe,
    SearchRecipe, 
    ListRecipes
  },

  data() {
    return {
      recipes: [
          {
            id: 1,
            name: 'Ensopado de galinha'  
          },
          {
            id: 2,
            name: 'Risoto'
          },
          {
            id: 3,
            name: 'strogonoff'
          }
      ]
    }
  },

  methods: {
    addNewRecipe (newRecipe) {
      this.recipes = [...this.recipes, newRecipe];
    }
  }
}
</script>

<style>
  #app {
  display: flex;
  flex-direction: column;
  }

  #Card{
    display: flex; 
    flex-direction: row;
    justify-content: center;
    align-items: center;
  }

  #ListContent {
    display: flex; 
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

</style>
