// svelteversion/src/components/ListRecipes.svelte
<script>
    export let data;

    import { navigate } from "svelte-routing";
    const goToViewRecipe =  (recipeName) => {
        navigate(`/viewrecipe/${recipeName}`)
    }
</script>

<style>
    .CustomList {
        width: 77%;
    }

    .CustomCard {
        border: 2px solid;
        border-color: black;
        border-radius: 4px;
        padding: 0.6%;
        margin: 1%;
        font-weight: bold;
        text-align: center;
        cursor: pointer;
    }

    .CustomCard:hover {
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
    }
</style>


<div class="CustomList">
    {#each data as item}
        <div class="CustomCard" on:click={goToViewRecipe(item.name)}>
            {item.name}
        </div>
    {/each}
</div>

// angularversion/src/app/components/list-recipes/list-recipes.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { Recipes } from '../../models/Recipes';

@Component({
  selector: 'app-list-recipes',
  templateUrl: './list-recipes.component.html',
  styleUrls: ['./list-recipes.component.css']
})
export class ListRecipesComponent implements OnInit {

  @Input() Data:Recipes[];

  constructor(private router: Router) { }

  goToSearch(recipeName) {
    this.router.navigate(['/view-recipe', recipeName])
  }

  ngOnInit(): void {
  }

}



<style>
    #CustomCard {
        border: 2px solid;
        border-color: black;
        border-radius: 4px;
        padding: 0.6%;
        margin: 1%;
        font-weight: bold;
        text-align: center;
        cursor: pointer; 
    }

    #CustomCard:hover {
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
    }
</style>

<div *ngFor="let item of Data">
   <div id="CustomCard" (click)="goToSearch(item.name)">
       {{item.name}}
   </div>
</div>
