// angularversion/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { async } from '@angular/core/testing';
import {db} from '../firebase.js'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angularversion';
  recipes = [];

  async  renderData() {
    const snapshot = await db.collection("recipes").get();
      const loadingData = [];
      snapshot.forEach((doc) => {
        loadingData.push({
          id: doc.id,
          ...doc.data(),
        });
      });
      this.recipes = loadingData;
  };

  async handleNewRecipe() {
    var value = prompt('Digite a nova receita');

    if(value){
      await db.collection("recipes").add({
        name: value,
        calorias: 0
      })

      this.renderData();
      //this.recipes = [...this.recipes, {id: 4, name: value}];
    }
  }

  ngOnInit(): void {
    this.renderData();
  }
}

<style>
  #pricipalPage {
    display: flex;
    flex-direction: column;
  }

  #principalCard {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
  }

  #ListContent {
    display: flex; 
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  app-add-recipe {
        margin: 3.5%;
        border: 2px solid;
        border-color: #4834d4;
        border-radius: 4px;
        width: 30%;
        padding: 3%;
        text-align: center;
    }
  
    app-search-recipe {
      margin: 3.5%;
        border: 2px solid;
        border-color: #eb4d4b;
        border-radius: 4px;
        width: 30%;
        padding: 3%;
        text-align: center;
    }

    app-list-recipes {
      border: 2px solid;
      border-color: black;
      width: 77%;
      border-radius: 4px;
      padding: 1.2%;
    }

</style>





<div id="principalPage">
  <app-header></app-header>
  <div id="principalCard">
    <app-add-recipe (click)="handleNewRecipe()"></app-add-recipe>
    <app-search-recipe></app-search-recipe>
  </div>
  <div id="ListContent">
    <h2>Receitas Já adicionadas</h2>
    <app-list-recipes [Data] = "recipes"></app-list-recipes>
  </div>
</div>

// svelteversion/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import Header from './components/Header.svelte'
	import AddRecipe from './components/AddRecipe.svelte'
	import SearchRecipe from './components/SearchRecipe.svelte'
	import ListRecipes from './components/ListRecipes.svelte'
	import {db} from './firebase.js'

	let recipes = [];

	const renderData = async () => {
		const snapshot = await db.collection("recipes").get();
		const loadingData = [];
		snapshot.forEach((doc) => {
			loadingData.push({
			id: doc.id,
			...doc.data(),
			});
		});
		recipes = loadingData; 
	}
	  
	onMount( () => {
		renderData();
	});

	const handleNewRecipe = async () => {
		var value = prompt('Digite a nova receita');

		if(value){
			await db.collection("recipes").add({
				name: value,
				calorias: 0
			})

			renderData();

			//recipes = [...recipes, {id: 4, name: value}];
		}

  }
</script>

<style>

	#principal {
		display: flex;
		flex-direction: column;
	}

	#card {
		display: flex; 
    	flex-direction: row;
    	justify-content: center;
    	align-items: center;
	}

	#ListContent {
		display: flex; 
		flex-direction: column; 
		justify-content: center; 
		align-items: center;
	}

</style>

<div id="principal">
	<Header />
	<div id="card">
		<AddRecipe on:addrecipe={handleNewRecipe}/>
		<SearchRecipe />
	</div>

	<div id="ListContent">
		<h2>Receitas já adicionadas</h2>
		<ListRecipes data={recipes}/>
	</div>
</div>
