// vueversion/src/views/ViewRecipe.vue
<template>
    <div>
        <div class="container">
            <div class="body">
                <div id="ViewRecipeBody">
                    <p class="Title">Name</p>
                    {{correspondRecipes[0].name}}
                    <div class="Line" />

                    <p class="Title">Calories</p>
                    {{correspondRecipes[0].calorias}}
                    <div class="Line" />

                    <p class="Title">Recipe</p>
                    {{correspondRecipes[0].recipe}}
                    <div class="Line" />
                </div>
            
            </div>  
        </div>    
    </div>
</template>

<script>
    import { mapGetters} from 'vuex'
    export default {
        name: 'ViewRecipe',
        data () {
            return {
                correspondRecipes: [],
                recipeName: this.$route.params.name
            }
        },

        computed: {
        ...mapGetters({
        recipes: 'recipes'
        })
        },

        methods: {
            filterRecipes() {
                if(this.recipeName !== ''){
                    const matchedRecipes = this.recipes.filter(item => {
                        return item.name.includes(this.recipeName)})
                
                    if(matchedRecipes) {
                        this.correspondRecipes = matchedRecipes
                    }
                }
            }
        },

        mounted () {
             this.filterRecipes();
        }
    }
</script>

<style>
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .body {
        display: flex; 
        flex-direction: column; 
        justify-content: center; 
        align-items: center; 
        width: 100%;
    }

     #ViewRecipeBody {
        width: 60%;
        text-align: center;
        
    }

     .Title {
        font-size: 30px;
        font-weight: bold;
        text-align: center;

    }

     .Line {
        margin-top: 2%;
        border-bottom: 1px solid;
        
    }
</style>

// angularversion/src/app/views/view-recipe/view-recipe.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from "@angular/router";
import { RecipesHookService } from '../../components/recipes-hook.service';

@Component({
  selector: 'app-view-recipe',
  templateUrl: './view-recipe.component.html',
  styleUrls: ['./view-recipe.component.css']
})
export class ViewRecipeComponent implements OnInit {

  constructor(private route: ActivatedRoute, public recipeService: RecipesHookService) { }

  recipeName = ''
  correspondRecipes = []

  filterRecipes () {
    if(this.recipeName !== ''){
        let matchedRecipes = this.recipeService.recipes.filter(item => {
            return item.name.includes(this.recipeName)})
        if(matchedRecipes) {
            this.correspondRecipes = matchedRecipes;
        }
    }
    
}

  ngOnInit(): void {
    this.route.params.subscribe( param => this.recipeName = param.name);
    this.filterRecipes();
    
  }

}

<div>
    <div class="container">
        <div class="body">
            <div id="ViewRecipeBody">
                <p class="Title">Name</p>
                {{correspondRecipes[0].name}}
                <div class="Line"></div>

                <p class="Title">Calories</p>
                {{correspondRecipes[0].calorias}}
                <div class="Line"></div>

                <p class="Title">Recipe</p>
                {{correspondRecipes[0].recipe}}
                <div class="Line"></div>
            </div>
        
        </div>  
    </div>    
</div>

<style>
     .container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .body {
        display: flex; 
        flex-direction: column; 
        justify-content: center; 
        align-items: center; 
        width: 100%;
    }

     #ViewRecipeBody {
        width: 60%;
        text-align: center;
        
    }

     .Title {
        font-size: 30px;
        font-weight: bold;
        text-align: center;

    }

     .Line {
        margin-top: 2%;
        border-bottom: 1px solid;
        
    }
</style>
