// svelteversion/src/components/Header.svelte
<style>
    .CustomHeader {
        font-family: Avenir, Helvetica, Arial, sans-serif;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 1.2%;
        border-bottom: 3px solid;
        width: 100%;
    }
</style>

<div class="CustomHeader">
    RECIPE HANDLER
</div>

// vueversion/src/components/Header.vue
<template>
    <div class="cuco">
        RECIPE HANDLER
    </div>
</template>

<script>
export default {
    name: 'Header'
}
</script>

<style scoped>
    .cuco{
        font-family: Avenir, Helvetica, Arial, sans-serif;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 1.2%;
        border-bottom: 3px solid;
        width: 100%;
    
    };
</style>
